# Generated by Django 3.2.6 on 2021-08-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question',
            field=models.TextField(default=False, verbose_name='Вопрос'),
        ),
    ]
