# Generated by Django 3.2.6 on 2021-08-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questions_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('question', models.TextField(default=False, verbose_name='Вопрос')),
                ('is_unswerd', models.BooleanField(default=True, verbose_name='Ответил?')),
            ],
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
