# Generated by Django 3.2.6 on 2021-08-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('editor_name', models.CharField(default=False, max_length=55, verbose_name='Автор новости')),
            ],
        ),
    ]
